### ISSUE TITLE
Button Color for both states

### ISSUE THREAD

**Issue by EnnaKenT** [zcweng/SwitchButton#41]
Plz add 
"sb_uncheck_button_color"
"sb_check_button_color"
attributes

**Comment by vivekios** [comment]
How can i change the color from code.
For example: i have online / offline state. 
For online: it becomes green.
For offline: gray color
Now suppose at some point of time i want to show busy instead of online.
For busy i want to change the on color state to red.
How to make this at runtime from code ?

**Comment by zcweng** [comment]
thank u for pull requests. merged
